### ISSUE TITLE
Conditional compile for SoftwareSerial? [Feature Request]

### ISSUE THREAD

**Issue by int3ll3ct** [smarmengol/Modbus-Master-Slave-for-Arduino#10]
The mandatory aspect of the SoftwareSerial feature causes a __vector_3 clash in my Arduino project.  The problem has to do with multiple libraries wanting to supply the same interrupt handlers for different purposes.  My proposal would be to modify this library to conditionally compile in software serial support.  I'll give it a go and if successful will propose the change...

**Comment by alextingle** [comment]
My solution (see pull request) just removes any dependency upon SoftwareSerial OR HardwareSerial classes. They both inherit from the "Stream" interface, and that's all Modbus now uses. Example:

HardwareSerial example:

    Modbus slave(1,Serial);
    void setup() {
      Serial.begin(19200);
      slave.start();
    }

SoftwareSerial example:

    SoftwareSerial mySerial(3, 5);
    Modbus slave(1,mySerial);
    void setup() {
      mySerial.begin(19200);
      slave.start();
    }
