### ISSUE TITLE
implementation of  Modbus Master/Slave on Arduino Mega 

### ISSUE THREAD

**Issue by msamiryusuf** [smarmengol/Modbus-Master-Slave-for-Arduino#14]
Dear Modbus-Master-Slave-for-Arduino Creator

i am trying to read from 2 serial interfaces one is the native serial which is TX0/RX0 as Master and i need to implement modbus slave on TX1/RX1,Master MODBUS to will communication with other devices and MODBUS slave  it will communicate with my SCADA system and it will get all the data required from the modbus master , the question is how i can link between them and the data that polled from the modbus master how i can assign it to my scada through the 2nd Com port

this is FYI

REGARDS

**Comment by smarmengol** [comment]
Dear Mr Mohammed,

The data exchange is performed through an array. This blog covers the
questions that you are asking :

https://arduino-experience.blogspot.com.es/?m=1

Hope this helps you!

Good luck!

SAMUEL MARCO

El dia 16/08/2016 08:00, "msamiryusuf" <notifications@github.com> va
escriure:
