### ISSUE TITLE
Analogic input a output doesn't work

### ISSUE THREAD

**Issue by huertarga** [smarmengol/Modbus-Master-Slave-for-Arduino#16]
Good morning Samuel , I tried your library MODBUS my arduino MEGA , and it works well with records 0 and 1 , but when I have an analog output or measurement records 3 and 4 seem to me offline and do not work even using the example you have in the library with any Arduino .

Could I help take measurements even register 3 ?

Thanks , I'm using as master the IOServer and USB serial connection

**Comment by smarmengol** [comment]
Hi,
The slave works fine. Have You tried it with a different master? I mean Qmodbus or modpoll.

http://arduino-experience.blogspot.com/2014/03/another-modbus-slave-example.html

Regards,
