### ISSUE TITLE
No response from Modbus slave

### ISSUE THREAD

**Issue by Jayesh023** [smarmengol/Modbus-Master-Slave-for-Arduino#25]
I have loaded this program and when it runs it shows no data on the virtual terminal in Proteus
this is the program

`#include` <ModbusRtu.h>
// data array for modbus network sharing
uint16_t au16data[16] = {
  3, 1415, 9265, 4, 2, 7182, 28182, 8, 0, 0, 0, 0, 0, 0, 1, -1 };

/**
 *  Modbus object declaration
 *  u8id : node id = 0 for master, = 1..247 for slave
 *  u8serno : serial port (use 0 for Serial)
 *  u8txenpin : 0 for RS-232 and USB-FTDI 
 *               or any pin number > 1 for RS-485
 */
Modbus slave(1,0,0); // this is slave @1 and RS-232 or USB-FTDI
void setup() {
  slave.begin( 19200 ); // baud-rate at 19200
}
void loop() {
  slave.poll( au16data, 16 );
}

Have any one worked on this library and got success?

![untitled](https://user-images.githubusercontent.com/30001040/27985180-2c285b86-6404-11e7-8881-3e8ea3f5495a.png)

**Comment by smarmengol** [comment]
Hi,

I've never used Proteus for these things. This library works with
physical devices, but it is difficult to simulate it (as all of this
stuff). I checked it with an LCD, which showed the contents of a set of
registers.

Regards,

El ds 08 de 07 de 2017 a les 12:08 +0000, en/na Jayesh023 va escriure:
