### ISSUE TITLE
Interface arduino (slave) and PC (master) problem

### ISSUE THREAD

**Issue by Guitargang** [smarmengol/Modbus-Master-Slave-for-Arduino#28]
I search for modbus library from google and found your library which is very famous. I tried to use your example code to my arduino mega 2560 but when I tried to connect to PC. it show timeout. Please advise how to use your library with mega 2560 ? Thank you.

**Comment by smarmengol** [comment]
Please look at this link:

https://arduino-experience.blogspot.com/2016/02/data-frame-settings-for-serial.html
