### ISSUE TITLE
 Master functions in Function code 1 ,2 and 15 still not implemented.Why？

### ISSUE THREAD

**Issue by ouyangxin95** [smarmengol/Modbus-Master-Slave-for-Arduino#29]
Hi,Samuel Smarmengol.
    I learned your code on GitHub-《Modbus-Master-Slave-for-Arduino》.This work is fantastic,because it uses a lock free delay and almost all functions of Modbus communication are implemented.This is one of the best Arduino library functions I've ever used.Thanks for your contribution.
    But I found Master functions in Function code 1 ,2 and 15 still not implemented.Why？What's the trouble with you?
    What should I do if I want to implement Function code 2?I would appreciate it if you help me.

**Comment by smarmengol** [comment]
This library was written between 2009 and 2013. I decided to publish my work in order to let others to finish it. Unfortunately human nature is lazy and other people only want you to make profit with your work.
Are you going to pay me for finishing this work???
