### ISSUE TITLE
Setting parameters(coils) in slave with the library

### ISSUE THREAD

**Issue by pkrulz** [smarmengol/Modbus-Master-Slave-for-Arduino#32]
Hi
Is the library only capable of sending its data to the master or can it also take commands from the master to set its parameter.

I understand that this is a question, not exactly an issue and sorry for posting it here as I was not sure where else it would go.

Regards
Pradeep

**Comment by pkrulz** [comment]
I guess I understood it how to do that. We can write to array using modbus commands of writing to coils or registers. 

Thanks

**Comment by smarmengol** [comment]
Yes, that's correct.

El dia 16/12/2017 5:51 p. m., "pkrulz" <notifications@github.com> va
escriure:
