### ISSUE TITLE
Compline error on 32u4 

### ISSUE THREAD

**Issue by shmrymbd** [smarmengol/Modbus-Master-Slave-for-Arduino#33]
Hi a have this error when compling sample on 32u4. pls advice.
`arduino_modified_sketch_652641/software_serial_simple_master.ino:42:0:
Arduino/libraries/Modbus-Master-Slave-for-Arduino-master/ModbusRtu.h: In member function 'void Modbus::begin(long int)':

Arduino/libraries/Modbus-Master-Slave-for-Arduino-master/ModbusRtu.h:316:14: error: cannot convert 'Serial_*' to 'HardwareSerial*' in assignment
         port = &Serial;

              ^
Arduino/libraries/Modbus-Master-Slave-for-Arduino-master/ModbusRtu.h: In member function 'void Modbus::begin(long int, uint8_t)':
Arduino/libraries/Modbus-Master-Slave-for-Arduino-master/ModbusRtu.h:399:14: error: cannot convert 'Serial_*' to 'HardwareSerial*' in assignment
         port = &Serial;

              ^
Arduino/libraries/Modbus-Master-Slave-for-Arduino-master/ModbusRtu.h: In member function 'void Modbus::sendTxBuffer()':
Arduino/libraries/Modbus-Master-Slave-for-Arduino-master/ModbusRtu.h:924:13: error: 'UCSR0A' was not declared in this scope
             UCSR0A=UCSR0A |(1 << TXC0);

             ^
Arduino/libraries/Modbus-Master-Slave-for-Arduino-master/ModbusRtu.h:924:34: error: 'TXC0' was not declared in this scope
             UCSR0A=UCSR0A |(1 << TXC0);

                                  ^
Arduino/libraries/Modbus-Master-Slave-for-Arduino-master/ModbusRtu.h:960:22: error: 'UCSR0A' was not declared in this scope
             while (!(UCSR0A & (1 << TXC0)));

                      ^
Arduino/libraries/Modbus-Master-Slave-for-Arduino-master/ModbusRtu.h:960:37: error: 'TXC0' was not declared in this scope
             while (!(UCSR0A & (1 << TXC0)));`

**Comment by Gusev-Roman** [comment]
library is not compatible with Arduino Leonardo yet)
