### ISSUE TITLE
 register platformIO library

### ISSUE THREAD

**Issue by dongly** [smarmengol/Modbus-Master-Slave-for-Arduino#4]
PlatformIO is a good open source ecosystem for IoT development
Cross-platform build system. Continuous and IDE integration. Arduino and ARM mbed compatible
It is  a good choice that register the library on PlatromIO.
[http://docs.platformio.org/en/latest/librarymanager/creating.html](http://docs.platformio.org/en/latest/librarymanager/creating.html)

**Comment by smarmengol** [comment]
Thanks
