### ISSUE TITLE
How to change program for Serial 1 port on Arduino Mega?

### ISSUE THREAD

**Issue by ronie19** [smarmengol/Modbus-Master-Slave-for-Arduino#42]
If I want to change serial port to Tx1, Rx1 or pin 19 and 18 on Arduino Mega other than default port then how can it be done? The arduino device is going to be a slave device. Kindly guide the changes to be made.

**Comment by smarmengol** [comment]
Dear Ronie19,

When the Modbus object is being declared,

/**
 *  Modbus object declaration
 *  u8id : node id = 0 for master, = 1..247 for slave
 *  u8serno : serial port (use 0 for Serial)
 *  u8txenpin : 0 for RS-232 and USB-FTDI 
 *               or any pin number > 1 for RS-485
 */
Modbus slave(1,0,0); // this is slave @1 and RS-232 or USB-FTDI

You should replace it and write:

Modbus slave(1,1,0); // this is slave @1 and RS-232 or USB-FTDI

This second 1 is the Serial1 port. If you need to use Serial2 or Serial3, just put a 2 or a 3. 
Regards,
