### ISSUE TITLE
how to setup Serial settings: parity, stop bits

### ISSUE THREAD

**Issue by taiwansensor** [smarmengol/Modbus-Master-Slave-for-Arduino#44]
hello , i have a rs485 slave, it's need setup serial for  8N2 (Serial settings: parity, stop bits ) , how can i set it ?

**Comment by smarmengol** [comment]
Hello @taiwansensor ,
Your issue is explained here:
http://arduino-experience.blogspot.com/2016/02/data-frame-settings-for-serial.html
I hope this helps!
Cheers
