### ISSUE TITLE
Which tool to use for Modbus slave on Linux

### ISSUE THREAD

**Issue by sagartec** [smarmengol/Modbus-Master-Slave-for-Arduino#62]
I want to use Modbus RTU master and i have planned to use this library. I know this question is not related to the code but i want suggestion on tool. I am using Linux and i am not able to find proper tool for mobus.

**Comment by aleksander1084** [comment]
Hi,
I'm using ModScan but it's for Windows. If you are looking just for a Modbus monitor there is similar app for both windows and linux available here: https://github.com/ed-chemnitz/qmodbus

If you are planing to use PC as PLC and implement logic on it you probably will have to look for specific linux distribution concentrated on Real time operation

**Comment by dmikushin** [comment]
You can also use `pymodbus` Python library.
