### ISSUE TITLE
Using Library in STM32

### ISSUE THREAD

**Issue by elhamsut** [smarmengol/Modbus-Master-Slave-for-Arduino#66]
Hello, I want to use this library in STM32F103. I saw you have a complete CubeMX project. But I cannot realize how to use it? Would you please provide a detailed document for using this great library?

**Comment by smarmengol** [comment]
Dear Elhamsut,
There is a documentation for this library. In order to use it in other devices, just emulate the Arduino's "Serial" library.
You may find information here: https://www.stm32duino.com/
Regards,
