### ISSUE TITLE
Is there an example of how to specify the address of a register?

### ISSUE THREAD

**Issue by rkertesz** [smarmengol/Modbus-Master-Slave-for-Arduino#7]
The registers in the examples start at address 0. Is there a recommended method to start at 1000, for example?

**Comment by smarmengol** [comment]
It depends on the Modbus function. For the Master, there is no problem. The thing is a little more complex for the slave, which should require an offset address.

**Comment by shivalingaraju** [comment]
In the Arduino code, you can change it to 1000 instead of 0 your work will be done.

**Comment by alextingle** [comment]
I'm working on a shim that should add address mapping to the slave, without adding too much extra to the memory needs.

**Comment by Gio-dot** [comment]
> It depends on the Modbus function. For the Master, there is no problem. The thing is a little more complex for the slave, which should require an offset address.

Hi, how can be added this offset address?
