### ISSUE TITLE
Receive missing data CRC - STM32 - Sofware serial

### ISSUE THREAD

**Issue by NgHieuPickon** [smarmengol/Modbus-Master-Slave-for-Arduino#74]
Hello, 
I recently used your library for my project with STM32G030K8T6 and Software serial.
(https://github.com/stm32duino/Arduino_Core_STM32/wiki)
when I receive the data, all packet data is missing the last CRC byte at Baurate 9600 - 8N1.
I don't know real reason, but adding "delay(2)" after "while ( u32overTimeCountDown-- > 0);", that work well.
Look like:
void Modbus::sendTxBuffer()
{
..........

    if (u8txenpin > 1)
    {
    ..........
        volatile uint32_t u32overTimeCountDown = u32overTime;
        while ( u32overTimeCountDown-- > 0);
        delay(2);       //Hieu edit
        digitalWrite( u8txenpin, LOW );
    ..........
}
I think this issue needs to be researched and fixed in the latest update.

**Comment by smarmengol** [comment]
Hi,
This library wasn't intented for software serial, so these issues may happen. I discourage the use of delay instructions, because they could affect its performance, particularly in huge networks.
Regards
